### ISSUE TITLE
Exception using Subscribe on Accelerometer on iOS 11.3

### ISSUE THREAD

**Issue by nicolas-garcia** [aritchie/sensors#11] opened 2018-05-16 14:26 UTC
Hello!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP (not tested)
 - [ ] .NET Standard (not tested)

## Version of OS(s) listed above with issue
iOS 11.3.1

## Version of ACR Sensor Plugin Library
v2.4.0

## Expected Behaviour

Using the following code works fine on Android, but not on iOS:
```csharp
// Just here as example
private readonly ConcurrentQueue<IList<MotionReading>> _workQueue;

// Initialized in constructor by dependency injection
private IAccelerometer Accelerometer { get; } 

public void StartDetection()
{
    if (!this.Accelerometer.IsAvailable)
        return;
    var sampleTime = TimeSpan.FromMilliseconds(400);
    try
    {
        this._subscription = this.Accelerometer.WhenReadingTaken() // Fine
                                 .Buffer(sampleTime) // Fine
                                 .Subscribe(this.OnAccelerometerMove); // Exception from here
    }
    catch (Exception e)
    {
        Console.WriteLine(e.ToString());
    }
}

private void OnAccelerometerMove(IList<MotionReading> motions)
{
   // This method is never called
    this._workQueue.Enqueue(motions); 
}
```

`_workQueue` is dequed in an other thread.

If I split my call into 3 statements, I can see that the exception come from `.Subscribe()` call.
`.WhenReadingTaken()` and `.Buffer()` went well

## Actual Behavior
- Exception type: `System.ArgumentNullException`
- Message: `"Value cannot be null.\nParameter name: queue"`
- StackTrace: 
```
  at CoreMotion.CMMotionManager.StartAccelerometerUpdates (Foundation.NSOperationQueue queue, CoreMotion.CMAccelerometerHandler handler) [0x00087] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/CoreMotion/CMMotionManager.g.cs:109 
  at Plugin.Sensors.AccelerometerImpl.Start (CoreMotion.CMMotionManager mgr, System.IObserver`1[T] ob) [0x00013] in <d3e064eb5ed74b1785c13365a4e54ac7>:0 
  at Plugin.Sensors.AbstractMotionSensor.<WhenReadingTaken>b__12_0 (System.IObserver`1[T] ob) [0x00000] in <d3e064eb5ed74b1785c13365a4e54ac7>:0 
  at System.Reactive.Linq.QueryLanguage+<>c__DisplayClass329_0`1[TSource].<Create>b__0 (System.IObserver`1[T] o) [0x00000] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.AnonymousObservable`1[T].SubscribeCore (System.IObserver`1[T] observer) [0x00000] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.ObservableBase`1[T].Subscribe (System.IObserver`1[T] observer) [0x00037] in <99f8205c51c44bb480747b577b8001ff>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow (System.Exception exception) [0x00006] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.ExceptionHelpers.Throw (System.Exception exception) [0x0000a] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Stubs+<>c.<.cctor>b__2_1 (System.Exception ex) [0x00000] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.AnonymousSafeObserver`1[T].OnError (System.Exception error) [0x0000e] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Linq.ObservableImpl.Buffer`1+BufferTimeShift[TSource].OnError (System.Exception error) [0x0001c] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Linq.ObservableImpl.RefCount`1+_[TSource].OnError (System.Exception error) [0x00000] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Subjects.Subject`1[T].OnError (System.Exception error) [0x00046] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Linq.ObservableImpl.AsObservable`1+_[TSource].OnError (System.Exception error) [0x00000] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.AutoDetachObserver`1[T].OnErrorCore (System.Exception exception) [0x00000] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.ObserverBase`1[T].Fail (System.Exception error) [0x0000e] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.ObservableBase`1[T].Subscribe (System.IObserver`1[T] observer) [0x00047] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00024] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Linq.ObservableImpl.AsObservable`1[TSource].Run (System.IObserver`1[T] observer, System.IDisposable cancel, System.Action`1[T] setSink) [0x0000f] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Producer`1[TSource].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00071] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.ConnectableObservable`2[TSource,TResult].Connect () [0x00019] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Linq.ObservableImpl.RefCount`1+_[TSource].Run () [0x00053] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Linq.ObservableImpl.RefCount`1[TSource].Run (System.IObserver`1[T] observer, System.IDisposable cancel, System.Action`1[T] setSink) [0x00010] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Producer`1[TSource].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00071] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Linq.ObservableImpl.Buffer`1+BufferTimeShift[TSource].Run () [0x0003d] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Linq.ObservableImpl.Buffer`1[TSource].Run (System.IObserver`1[T] observer, System.IDisposable cancel, System.Action`1[T] setSink) [0x00062] in <e9c1ccec51844dbd92b833a0b4bc960e>:0 
  at System.Reactive.Producer`1[TSource].Run (System.Reactive.Concurrency.IScheduler _, System.Reactive.Producer`1+State[TSource] x) [0x00000] in <99f8205c51c44bb480747b577b8001ff>:0 
  at (wrapper unknown) System.Object.gsharedvt_out()
  at System.Reactive.Concurrency.ScheduledItem`2[TAbsolute,TValue].InvokeCore () [0x00000] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Concurrency.ScheduledItem`1[TAbsolute].Invoke () [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Concurrency.CurrentThreadScheduler+Trampoline.Run (System.Reactive.Concurrency.SchedulerQueue`1[TAbsolute] queue) [0x00040] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState] (TState state, System.TimeSpan dueTime, System.Func`3[T1,T2,TResult] action) [0x00046] in <99f8205c51c44bb480747b577b8001ff>:0 
  at (wrapper unknown) System.Object.gsharedvt_in()
  at (wrapper unknown) System.Object.gsharedvt_out()
  at System.Reactive.Concurrency.LocalScheduler.Schedule[TState] (TState state, System.Func`3[T1,T2,TResult] action) [0x0000e] in <99f8205c51c44bb480747b577b8001ff>:0 
  at (wrapper unknown) System.Object.gsharedvt_in()
  at System.Reactive.Producer`1[TSource].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00069] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Producer`1[TSource].Subscribe (System.IObserver`1[T] observer) [0x0000e] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.ObservableExtensions.Subscribe[T] (System.IObservable`1[T] source, System.Action`1[T] onNext) [0x0002d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at xxxxxxx.xxxxxxxx.xxxxxxxx.StartDetection () [0x00051] in xxxxMY_FILE_xx.cs:xx 
```

Thank you for your time! 😃

**Comment by aritchie** [comment] 2018-05-16 16:19
Are you calling this from the background or something?

**Comment by aritchie** [comment] 2018-05-17 02:05
Should be fixed up now.  I haven't setup a test case for it though

**Closed by aritchie** 2018-05-17 02:05 UTC

**Comment by nicolas-garcia** [comment] 2018-05-17 07:00
I confirm the issue is fixed.
Thank you very much!

**Comment by aritchie** [comment] 2018-05-17 11:51
Thanks for letting me know.  For my own knowledge, was the caused by a background call for the accelerometer?

**Comment by nicolas-garcia** [comment] 2018-05-17 12:04
This call is not on the UI thread. I should have tested it, but it did not came to my mind at those moment.
Anyway, your fix resolved the issue 😄
